# Generated by Django 2.1.5 on 2019-01-31 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=70)),
                ('password', models.CharField(max_length=8)),
                ('phone', models.IntegerField(validators=[django.core.validators.RegexValidator(message='Phone number must be : 010 or 011 or 012 or 015.', regex='^01[0|1|2|5]([0-9]{8})$')])),
                ('pic', models.ImageField(upload_to='Users/static/Users/images')),
            ],
        ),
    ]
