# Generated by Django 2.1.5 on 2019-02-04 10:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Users/static/Users/images')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(code='Invalid Phone Number', message='Phone number must be : 010 or 011 or 012 or 015.', regex='^01[0|1|2|5][0-9]{8}$')])),
                ('facebook_profile', models.URLField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
