# Generated by Django 2.1.5 on 2019-02-02 18:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(code='Invalid Phone Number', message='Phone number must be : 010 or 011 or 012 or 015.', regex='^1[0|1|2|5][0-9]{8}$')]),
        ),
    ]
