# Generated by Django 2.1.5 on 2019-02-07 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20190205_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='hello', upload_to='Users/images'),
            preserve_default=False,
        ),
    ]
