# Generated by Django 2.1.5 on 2019-02-05 07:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_auto_20190205_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5, message='Max Rate Value is 5'), django.core.validators.MinValueValidator(1, message='Min Rate value is 1')]),
        ),
    ]
