# Generated by Django 2.1.5 on 2019-02-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20190202_1811'),
        ('Projects', '0003_auto_20190131_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Projects/static/Projects/images'),
        ),
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together={('user', 'project')},
        ),
    ]
