# Generated by Django 2.1.5 on 2019-02-02 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20190202_1811'),
        ('Projects', '0005_auto_20190202_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Users.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Users.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report_comment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Users.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report_project',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Users.User'),
            preserve_default=False,
        ),
    ]
